### PR TITLE
Adding AdminInfo MP

### PR DESCRIPTION
**Pull request by Juanito99**
Thanks for helping contribute to the MP Catalog.  Please check the contribution guidelines with any questions, then fill out the below blanks.

What does this add/fix? 
------------------------------
Adding a new MP

Does this close any currently open issues?
------------------------------------------
No

Any other comments?
-------------------
Hope I did it right ...

### CODE REVIEW

**Review by brandubh — COMMENTED** [review]
I fear this MP can have an high noise level, has anyone tested it in a production environment?

**Comment by P2P-Nathan** [comment]
I have not used this pack, but could import it into my environment this
week and see what is generated.

**Comment by Juanito99** [comment]
Used it in a ~800 machines environment with expected results. Got alerts for shares where everyone can write into as the NTFS permissions also opened the door for it. 

Looking forward to read your feedback. - I'm open for suggestions ^_^


PS: The noise which is generated can be put into relation to an outage  which might be caused by an incautious user whose computer got infected by Ransome. Some of those Ransome species scan the network for shares and infects all it can reach / it can write to.

**Comment by Juanito99** [comment]
Updated MP. - Added 'OS Info'. 
More on: https://github.com/Juanito99/AdminInfo_OpsMgr

**Comment by Juanito99** [comment]
Major update is coming soon. - I'll be back then :-)

**Comment by P2P-Nathan** [comment]
Hi Ruben,

I'd be glad to test your new version when its ready, I have a small
environment but can throw it in to see how it goes.
If some of the alerts look like they may be noisy/excessive, you could
start with them enable="false" and put a note in the readme explaining what
each workflow does and how to turn it on.

-Nathan

**Comment by Juanito99** [comment]
Hi Master Nathan,
 

cool, appreciated :-)

I understand Grand Grandini's concerns so I'll mute my monitors and describe it in the notes how to activate them.
 
Ruben

**Comment by Juanito99** [comment]
@brandubh @P2P-Nathan 
Virtuoso Daniele,
Dear Nathan,

I extended my AdminInfo - MP (currently not on GitHub) and would like to commit it to the catalog. 
To avoid a possible 'alert storm' I set the option 'Alert on state' to 'None'. - It can be enabled then later in the SCOM console by overriding it. - Unfortunately the alert description is gone. 
As the MP is sealed I can't change it in the console which makes the alert hard to interpret.

Do you have a suggestion for me?

**Comment by P2P-Nathan** [comment]
Hello Ruben,

When you override the 'alert on state', the description may return.

What happens currently when you override the setting?

Thanks,
Nathan

**Comment by Juanito99** [comment]
In my VSAE it looks like this:
image

When I then override the monitor to create an alert, the alert looks in the console like that:
image

@P2P-Nathan  @brandubh 
Any hint?

**Pull request closed without merging**
