### PR TITLE
Created ValidateContents.ps1 to assist in reducing catalog errors.  

### PR DESCRIPTION
**Pull request by P2P-Nathan**
Corrected mismatch errors that the script found.
Moved some files to match index names.

### CODE REVIEW

**Comment by ehrnst** [comment]
I see all corrections was caused by me, so i'm approving this :)

**Review by ehrnst — APPROVED** [review]

**Comment by clarkd** [comment]
I think @shadeon was working on even further validation tests here - with Pester etc. so you might want to connect with him before merging this.

**Comment by shadeon** [comment]
I have been, however mine is aimed at providing a good experience with an editor we can "recommend" (VSCode) along with build/test integration and snippets, so it's probably a bit further out.

Since this PR also includes a bunch of fixes (in the same commit) I think it's probably better to merge this for now, and then my PR can always remove the validation script if we decide the pester tests are the way to go..

(The main advantage to pester is that since it emits standard unit testing results, we can plug this into AppVeyor or TravisCI so that PRs can't be merged if the tests fail).

**Comment by P2P-Nathan** [comment]
Merging the PR, as @shadeon mentioned it should be pretty easy to remove the old validation script at a later date.  For now it provides an easy method to right-click and test from windows explorer.

There is a PowerShell script that creates new entries without the need for editing JSON, we could also attach the Pester tests to the end of to perform checks at that point.

**Pull request merged**
