### PR TITLE
Update details.json

### PR DESCRIPTION
**Pull request by tfziegler**
Thanks for helping contribute to the MP Catalog.  Please check the contribution guidelines with any questions, then fill out the below blanks.

What does this add/fix? 
------------------------------

This should fix the SQL Addendum version agnostic MP and update

Does this close any currently open issues?
------------------------------------------

Discovery of the SQL Addendum MP

Any other comments?
-------------------
…

### CODE REVIEW

**Comment by P2P-Nathan** [comment]
@tfziegler Thanks for your update, has the new Addendum MP changed names, or is the library an additional MP needed?

The system has one folder per MP and the folder name needs to match the index entry.  We didn't have a great method for required sub-libraries and if there are two MPs needed it might be best to create another entry in the index for the Library.

**Comment by tfziegler** [comment]
The display name and source name has changed.  I think Kevin did this somewhere around 7.0.32.0

[cid:93636d27-58a8-455b-ade0-47ae13d1b83e]


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Review by P2P-Nathan — COMMENTED** [review]
Addendum name updated and folder changed

**Review by P2P-Nathan — APPROVED** [review]
Updated the index entry and it looks good

**Pull request merged**
